title: "danhagg.github.io"
remote_theme: pmarsceill/just-the-docs
color_scheme: nil
search_enabled: true

include:
  - _pages

defaults:
  # _posts
  - scope:
      path: ""
      type: posts