title: "danhagg.github.io"
remote_theme: pmarsceill/just-the-docs
color_scheme: nil
search_enabled: true

# Define Jekyll collections
collections:
  # Define a collection named "docs", its documents reside in the "_docs" directory
  docs:
    permalink: "/:collection/:path/"
    output: true
